org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.219
loader_version_range=[4,)

create_version=6.0.10-280
ponder_version=1.0.82
flywheel_version=1.0.6
registrate_version=MC1.21-1.3.0+67

mod_id=create_nuclear_industry
mod_name=Create: Nuclear Industry
mod_license=All Rights Reserved
mod_version=0.1.0
mod_group_id=com.iksxh.create_nuclear_industry
mod_authors=IKSXH
mod_description=Create 风格的核工业附属模组。本版本提供可见的首个实验反应堆外壳样例。
