package com.iksxh.create_nuclear_industry.config;

import net.neoforged.fml.ModContainer;
import net.neoforged.fml.config.ModConfig;
import net.neoforged.neoforge.common.ModConfigSpec;

/** Server-side P1 numeric contract. Values are read by later simulation tasks. */
public final class P1ServerConfig {
    public static final ModConfigSpec SPEC;
    public static final Values VALUES;

    static {
        ModConfigSpec.Builder builder = new ModConfigSpec.Builder();
        VALUES = new Values(builder);
        SPEC = builder.build();
    }

    private P1ServerConfig() {
    }

    public static void register(ModContainer modContainer) {
        modContainer.registerConfig(ModConfig.Type.SERVER, SPEC);
    }

    public static final class Values {
        public final ModConfigSpec.DoubleValue baseHeatPerFuelBlockHuPerTick;
        public final ModConfigSpec.DoubleValue fuelBurnTimeHours;
        public final ModConfigSpec.DoubleValue coolantAbsorptionHuPerMb;
        public final ModConfigSpec.IntValue perPortFlowMbPerTick;
        public final ModConfigSpec.IntValue totalFlowCapMbPerTick;
        public final ModConfigSpec.DoubleValue damageHeatThresholdHuPerTick;
        public final ModConfigSpec.DoubleValue damageRatePerTickHuLoad;
        public final ModConfigSpec.DoubleValue damageTransferRate;
        public final ModConfigSpec.DoubleValue meltdownTriggerFraction;
        public final ModConfigSpec.IntValue meltdownCountdownTicks;

        private Values(ModConfigSpec.Builder builder) {
            builder.push("reactor");
            baseHeatPerFuelBlockHuPerTick = builder
                    .comment("Base heat generated by one fuel block per tick.")
                    .defineInRange("baseHeatPerFuelBlockHuPerTick", 1.0D, 0.0D, 1_000_000.0D);
            fuelBurnTimeHours = builder
                    .comment("Fuel burn duration for one fresh fuel assembly, in hours.")
                    .defineInRange("fuelBurnTimeHours", 3.0D, 0.001D, 1_000_000.0D);
            coolantAbsorptionHuPerMb = builder
                    .comment("Heat absorbed by one millibucket of compound coolant.")
                    .defineInRange("coolantAbsorptionHuPerMb", 1.0D, 0.0D, 1_000_000.0D);
            perPortFlowMbPerTick = builder
                    .comment("Maximum coolant flow through one port per tick.")
                    .defineInRange("perPortFlowMbPerTick", 100, 0, 1_000_000);
            totalFlowCapMbPerTick = builder
                    .comment("Maximum aggregate coolant flow through one reactor per tick.")
                    .defineInRange("totalFlowCapMbPerTick", 200, 0, 1_000_000);
            damageHeatThresholdHuPerTick = builder
                    .comment("Effective heat load threshold before integrity damage begins.")
                    .defineInRange("damageHeatThresholdHuPerTick", 0.25D, 0.0D, 1_000_000.0D);
            damageRatePerTickHuLoad = builder
                    .comment("Integrity damage per tick per HU/t of effective heat above threshold.")
                    .defineInRange("damageRatePerTickHuLoad", 0.00125D, 0.0D, 1_000_000.0D);
            damageTransferRate = builder
                    .comment("Four-way heat damage transfer coefficient.")
                    .defineInRange("damageTransferRate", 0.25D, 0.0D, 1.0D);
            meltdownTriggerFraction = builder
                    .comment("Fraction of effective fuel columns that triggers a meltdown countdown.")
                    .defineInRange("meltdownTriggerFraction", 0.20D, 0.0D, 1.0D);
            meltdownCountdownTicks = builder
                    .comment("Meltdown countdown duration in server ticks.")
                    .defineInRange("meltdownCountdownTicks", 900, 0, 20_000_000);
            builder.pop();
        }
    }
}
